version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: evaluacion_tecnica
      DB_USERNAME: julioespinoza15
      DB_PASSWORD: julioespinoza15
    volumes:
      - .:/app
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: julioespinoza15
      MYSQL_DATABASE: evaluacion_tecnica
      MYSQL_USER: julioespinoza15
      MYSQL_PASSWORD: julioespinoza15
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
